version: '3.8'

services:
  db:
    image: mysql:8
    container_name: b4you-mysql
    environment:
      MYSQL_DATABASE: b4you_db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
